spring:
  profiles:
    active: dev
  application:
    name: ConfigurationService
info:
  app:
    name: Configuration Service Application
    description: Service for Configuration
    version: 1.0.0