server:
  port: 8030
  servlet:
    context-path: /cus
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  profiles:
    include: native
  cloud:
    config:
      uri: http://localhost:8888
      profile: dev
