server:
  port: 8999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  profiles:
    include: native
  cloud:
    config:
      uri: http://localhost:8888
      name: OAuthConfig