server:
  port: 7999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  profiles:
    include: git
  cloud:
    config:
      uri: http://localhost:8888
      name: OAuthConfig