#server.port=8000
#server.servlet.context-path=/rs
#security.oauth2.resource.user-info-uri=https://api.github.com/user
#security.oauth2.resource.user-info-uri=http://localhost:9000/am/user
spring:
  profiles:
    active: dev
  application:
    name: RSService
info:
  app:
    name: RS Service Application
    description: Service for RS
    version: 1.0.0