#server.port=8000
#server.servlet.context-path=/rs
#security.oauth2.resource.user-info-uri=https://api.github.com/user
#security.oauth2.resource.user-info-uri=http://localhost:9000/am/user

server:
  port: 8000
  servlet:
    context-path: /rs
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9000/am/user
   