server:
  port: 9000
  servlet:
    context-path: /as
security:
  oauth2:
    client:
      client-id: dev123
      client-secret: pwd
      authorized-grant-types:
      - password
      - client_credential
      - authorization_code
      - refresh_token
      scope:
      - read
      - write
      - openid
      
