server:
  port: 9000
  servlet:
    context-path: /as
app:
  oauth2:
    jwt:
      signing-key: as466gf
    realm: TESTREALM
    client:
      client-id: dev123
      client-pwd: pwd
      token-validity: 3600
      refresh-token-validity: 21600
spring:
  profiles:
    include: native
  cloud:
    config:
      uri: http://localhost:8888
      profile: dev
     
      
