server:
  port: 9000
  servlet:
    context-path: /as
security:
  oauth2:
    client:
      client-id: qa123
      client-secret: pwd
      authorized-grant-types:
      - password
      - client_credential
      - authorization_code
      - refresh_token
      scope:
      - read
      - write
      - openid
spring:
  profiles:
    include: native
  cloud:
    config:
      uri: http://localhost:8888
      profile: qa     
