server:
  port: 8020
  servlet:
    context-path: /ps
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9000/as/user
spring:
  profiles:
    include: native
  cloud:
    config:
      uri: http://localhost:8888
      profile: dev       