server:
  port: 7000
eureka:
  instance:
    hostname: qa
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  profiles:
    include: native
  cloud:
    config:
      uri: http://localhost:8888
      profile: qa
      